# Data analysis with pandas

In [2]:
import pandas as pd

## Load data from CSV file into Pandas dataframe

In [4]:
countries_df = pd.read_csv('countries.csv')

In [5]:
countries_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987
1,Albania,Europe,2877800.0,78.57,2.89,11803.431
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839
3,Andorra,Europe,77265.0,83.73,NaN,NaN
4,Angola,Africa,32866268.0,61.15,NaN,5819.495
...,...,...,...,...,...,...
205,Vietnam,Asia,97338583.0,75.40,2.60,6171.884
206,Western Sahara,Africa,597330.0,70.26,NaN,NaN
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775

### Information of dataframe

In [6]:
countries_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   location                    210 non-null    object
 1   continent                   210 non-null    object
 2   population                  210 non-null    float64
 3   life_expectancy             207 non-null    float64
 4   hospital_beds_per_thousand  164 non-null    float64
 5   gdp_per_capita              183 non-null    float64
dtypes: float64(4), object(2)
memory usage: 10.0+ KB

## How many countries does the dataframe contain ?

In [8]:
num_countries = countries_df.shape[0]

In [10]:
print('There are {} countries in the dataset'.format(num_countries))

There are 210 countries in the dataset

## Retrieve a list of continents from the dataframe ?

In [11]:
continents = countries_df.continent.unique()

In [12]:
continents

array(['Asia', 'Europe', 'Africa', 'North America', 'South America',
       'Oceania'], dtype=object)

## What is the total population of all the countries listed in this dataset ?

In [13]:
total_population = countries_df.population.sum()

In [14]:
print('The total population is {}.'.format(int(total_population)))

The total population is 7757980095.

## What is the overall life expectancy across in the world ?

In [16]:
overall_life_expectancy = ((countries_df.life_expectancy * countries_df.population).sum() / total_population.sum())

In [17]:
overall_life_expectancy

np.float64(72.72165193409664)

## Create a dataframe containing 10 countries with the highest population ?

In [18]:
most_populous_df = countries_df.sort_values('population', ascending=False).head(10)

In [19]:
most_populous_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
41,China,Asia,1.439324e+09,76.91,4.34,15308.712
90,India,Asia,1.380004e+09,69.66,0.53,6426.674
199,United States,North America,3.310026e+08,78.86,2.77,54225.446
91,Indonesia,Asia,2.735236e+08,71.72,1.04,11188.744
145,Pakistan,Asia,2.208923e+08,67.27,0.60,5034.708
27,Brazil,South America,2.125594e+08,75.88,2.20,14103.452
141,Nigeria,Africa,2.061396e+08,54.69,NaN,5338.454
15,Bangladesh,Asia,1.646894e+08,72.59,0.80,3523.984
157,Russia,Europe,1.459345e+08,72.58,8.05,24765.954
125,Mexico,North America,1.289328e+08,75.05,1.38,17336.469

## Add a new column in countries_df to record the overall GDP per country (product of population & per capita GDP)

In [20]:
countries_df['gdp'] = (countries_df.population * countries_df.gdp_per_capita)

In [21]:
countries_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987,7.022622e+10
1,Albania,Europe,2877800.0,78.57,2.89,11803.431,3.396791e+10
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839,6.101364e+11
3,Andorra,Europe,77265.0,83.73,NaN,NaN,NaN
4,Angola,Africa,32866268.0,61.15,NaN,5819.495,1.912651e+11
...,...,...,...,...,...,...,...
205,Vietnam,Asia,97338583.0,75.40,2.60,6171.884,6.007624e+11
206,Western Sahara,Africa,597330.0,70.26,NaN,NaN,NaN
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147,4.411699e+10
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251,6.782303e+10
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775,2.823622e+10

## Create a dataframe containing 10 countries with the lowest GDP per capita, among the counties with population greater than 100 million

In [22]:
required_df = countries_df[countries_df.population > 1e8].sort_values('gdp_per_capita').head(10)

In [28]:
required_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp
63,Ethiopia,Africa,1.149636e+08,66.60,0.30,1729.927,1.988786e+11
15,Bangladesh,Asia,1.646894e+08,72.59,0.80,3523.984,5.803628e+11
145,Pakistan,Asia,2.208923e+08,67.27,0.60,5034.708,1.112128e+12
141,Nigeria,Africa,2.061396e+08,54.69,NaN,5338.454,1.100467e+12
90,India,Asia,1.380004e+09,69.66,0.53,6426.674,8.868838e+12
151,Philippines,Asia,1.095811e+08,71.23,1.00,7599.188,8.327273e+11
58,Egypt,Africa,1.023344e+08,71.99,1.60,10550.206,1.079649e+12
91,Indonesia,Asia,2.735236e+08,71.72,1.04,11188.744,3.060386e+12
27,Brazil,South America,2.125594e+08,75.88,2.20,14103.452,2.997821e+12
41,China,Asia,1.439324e+09,76.91,4.34,15308.712,2.203419e+13

## Create a data frame that counts the number countries in each continent ?

In [29]:
country_counts_df = countries_df.groupby('continent').count()

In [30]:
country_counts_df

,location,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp
continent,,,,,,
Africa,55,55,55,40,53,53
Asia,47,47,47,43,45,45
Europe,51,51,48,43,42,42
North America,36,36,36,23,27,27
Oceania,8,8,8,3,4,4
South America,13,13,13,12,12,12

## Create a data frame showing the total population of each continent ?

In [34]:
countries_df = countries_df.drop(columns=['location'])

In [35]:
continent_populations_df = countries_df.groupby('continent').sum()

In [36]:
continent_populations_df

,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp
continent,,,,,
Africa,1.339424e+09,3532.41,60.220,288523.368,6.149204e+12
Asia,4.607388e+09,3506.05,124.930,1032210.905,5.676188e+13
Europe,7.485062e+08,3829.40,222.078,1401145.971,2.435885e+13
North America,5.912425e+08,2760.60,53.280,584691.580,2.266297e+13
Oceania,4.095832e+07,609.69,8.750,93260.722,1.354559e+12
South America,4.304611e+08,982.53,24.820,166089.423,6.258200e+12